name: GSEVT
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - plyfile
  - munch
  - natsort
  - numpy
  - Pillow
  - plyfile
  - PyOpenGL
  - PyYAML
  - scipy
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - tqdm
  - mkl=2024.0
  - pip:
    - ninja
    - opencv-python
    - open3d
    - pycryptodomex
    - gnupg
    - catkin-tools
    - rospkg
    - empy
    - submodules/diff-gaussian-rasterization

