Event:
  data_path: /home/liutao/JYA/GS-EVT/data/VECTOR/board_slow1/events.txt
  distortion_factors:
  - -0.39712487
  - 0.2030699
  - 0.00073509
  - 0.00397014
  - 0.16977825
  filter_threshold: 0.1
  img_height: 260
  img_width: 346
  intrinsic:
    cols: 3
    data:
    - 327.32749
    - 0.0
    - 304.97749
    - 0.0
    - 327.46184
    - 235.37621
    - 0.0
    - 0.0
    - 1.0
    dt: d
    rows: 3
  max_events_per_frame: 30000
Gaussian:
  calib_params:
    fx: 96.01292959477009
    fy: 97.16584166899645
  model_params:
    background:
    - 0
    - 0
    - 0
    device: cuda
    model_path: /home/liutao/JYA/GS-EVT/data/VECTOR/board_slow1/point_cloud.ply
    sh_degree: 3
  pipeline_params:
    compute_cov3D_python: false
    convert_SHs_python: false
Optimizer:
  cam_rot_delta: 0.003
  cam_trans_delta: 0.001
  cam_v_delta: 0.0001
  cam_w_delta: 1.0e-05
  converged_threshold: 0.0001
  max_optim_iter: 200
Tracking:
  initial_pose:
    rot:
      cols: 3
      data:
      - 0.98657657
      - 0.04369101
      - 0.15734604
      - -0.0402753
      - 0.99887998
      - -0.02483318
      - -0.1582548
      - 0.01816268
      - 0.98723125
      dt: d
      rows: 3
    trans:
      cols: 1
      data:
      - 2.24311095
      - 2.63636504
      - 0.70613384
      dt: d
      rows: 3
  initial_vel:
    angular_vel:
    - -0.00748658
    - 0.01953471
    - 0.00479119
    linear_vel:
    - -0.80285077
    - -0.35492166
    - 0.0134317
