Event:
  data_path: /home/liutao/JYA/GS-EVT/data/VECTOR/corner_slow1/events.txt
  distortion_factors:
  - -0.39712487
  - 0.2030699
  - 0.00073509
  - 0.00397014
  - 0.16977825
  filter_threshold: 0.1
  img_height: 480
  img_width: 640
  intrinsic:
    cols: 3
    data:
    - 327.32749
    - 0.0
    - 304.97749
    - 0.0
    - 327.46184
    - 235.37621
    - 0.0
    - 0.0
    - 1.0
    dt: d
    rows: 3
  max_events_per_frame: 30000
Gaussian:
  calib_params:
    fx: 898.6876142609614
    fy: 898.5200991810121
  model_params:
    background:
    - 0
    - 0
    - 0
    device: cuda
    model_path: /home/liutao/JYA/GS-EVT/data/VECTOR/corner_slow1/point_cloud.ply
    sh_degree: 3
  pipeline_params:
    compute_cov3D_python: false
    convert_SHs_python: false
Optimizer:
  cam_rot_delta: 0.003
  cam_trans_delta: 0.001
  cam_v_delta: 0.0001
  cam_w_delta: 1.0e-05
  converged_threshold: 0.0001
  max_optim_iter: 200
Tracking:
  initial_pose:
    rot:
      cols: 3
      data:
      - 0.99892939
      - -0.01565589
      - -0.04353129
      - 0.0315167
      - 0.91914409
      - 0.39265867
      - 0.03386411
      - -0.39361025
      - 0.91865347
      dt: d
      rows: 3
    trans:
      cols: 1
      data:
      - 4.88670818e-04
      - 1.10975686e+00
      - 3.90329394e-01
      dt: d
      rows: 3
  initial_vel:
    angular_vel:
    - -0.03473915
    - 0.15820262
    - 0.00923435
    linear_vel:
    - 1.65985219
    - 0.36254188
    - 2.7903562
