Event:
  data_path: /home/liutao/data/VECTOR/desk_normal1/events.txt
  distortion_factors:
  - -0.031982
  - 0.041966
  - -0.000507
  - -0.001031
  - 0.000000
  filter_threshold: 0
  img_height: 480
  img_width: 640
  intrinsic:
    cols: 3
    data:
    - 327.32749
    - 0.0
    - 304.97749
    - 0.0
    - 327.46184
    - 235.37621
    - 0.0
    - 0.0
    - 1.0
    dt: d
    rows: 3
  gaussian_kernel_size: 9
  max_events_per_frame: 30000

Gaussian:
  calib_params:
    fx: 327.32749
    fy: 327.46184
  model_params:
    background:
    - 0
    - 0
    - 0
    device: cuda
    model_path: /home/liutao/data/VECTOR/desk_normal1/point_cloud.ply
    sh_degree: 3
  pipeline_params:
    compute_cov3D_python: false
    convert_SHs_python: false
  img_height: 480
  img_width: 640

Optimizer:
  cam_rot_delta: 0.004
  cam_trans_delta: 0.004
  cam_v_delta: 0.002
  cam_w_delta: 0.002
  converged_threshold: 0.0001
  max_optim_iter: 200

Tracking:
  initial_pose:
    rot:
      cols: 3
      data:
      - 0.96273041
      - 0.13706175
      - -0.23316138
      - -0.15101728
      - 0.98759518
      - -0.04300630
      - 0.22437454
      - 0.07661487
      - 0.97148661
      dt: d
      rows: 3
    trans:
      cols: 1
      data:
      - -3.99364391
      - 2.07062047
      - -1.35796279
      dt: d
      rows: 3
  initial_vel:
    angular_vel:
    - 0.0025
    - 0.0009
    - 0.0010
    linear_vel:
    - 0.0134
    - 0.1050
    - 0.0996
  save_path: /home/liutao/Project/GS-EVT/results/desk_normal1