Event:
  data_path: /home/liutao/JYA/GS-EVT/data/VECTOR/desk_normal1/events.txt
  distortion_factors:
  - -0.031982
  - 0.041966
  - -0.000507
  - -0.001031
  - 0.000000
  filter_threshold: 0
  img_height: 480
  img_width: 640
  intrinsic:
    cols: 3
    data:
    - 327.32749
    - 0.0
    - 304.97749
    - 0.0
    - 327.46184
    - 235.37621
    - 0.0
    - 0.0
    - 1.0
    dt: d
    rows: 3
  max_events_per_frame: 30000
Gaussian:
  calib_params:
    fx: 327.32749
    fy: 327.46184
  model_params:
    background:
    - 0
    - 0
    - 0
    device: cuda
    model_path: /home/liutao/JYA/GS-EVT/data/VECTOR/desk_normal1/point_cloud.ply
    sh_degree: 3
  pipeline_params:
    compute_cov3D_python: false
    convert_SHs_python: false
  img_height: 480
  img_width: 640
Optimizer:
  cam_rot_delta: 0.0015
  cam_trans_delta: 0.001
  cam_v_delta: 0.0015
  cam_w_delta: 0.0015
  converged_threshold: 0.0001
  max_optim_iter: 200
Tracking:
  initial_pose:
    rot:
      cols: 3
      data:
      - 0.96292812
      - 0.14208335
      - -0.22930713
      - -0.15980243
      - 0.98529015
      - -0.06055166
      - 0.21733068 
      - 0.09495074
      - 0.97146885
      dt: d
      rows: 3
    trans:
      cols: 1
      data:
      - -4.00863129
      - 2.49847997
      - -1.25266063
      dt: d
      rows: 3
  initial_vel:
    angular_vel:
    - -0.00174768
    - -0.00616931
    - 0.00683319
    linear_vel:
    - 0.02366218
    - 0.00654004
    - 0.00170499
