Event:
  data_path: /home/liutao/data/VECTOR/sofa_normal1/events.txt
  distortion_factors:
  - -0.031982
  - 0.041966
  - -0.000507
  - -0.001031
  - 0.000000
  img_height: 480
  img_width: 640
  intrinsic:
    cols: 3
    data:
    - 327.32749
    - 0.0
    - 304.97749
    - 0.0
    - 327.46184
    - 235.37621
    - 0.0
    - 0.0
    - 1.0
    dt: d
    rows: 3
  gaussian_kernel_size: 9
  max_events_per_frame: 30000

Gaussian:
  calib_params:
    fx: 327.32749
    fy: 327.46184
  model_params:
    background:
    - 0
    - 0
    - 0
    device: cuda
    model_path: /home/liutao/data/VECTOR/sofa_normal1/point_cloud.ply
    sh_degree: 3
  pipeline_params:
    compute_cov3D_python: false
    convert_SHs_python: false
  img_height: 480
  img_width: 640

Optimizer:
  cam_rot_delta: 0.004
  cam_trans_delta: 0.004
  cam_v_delta: 0.002
  cam_w_delta: 0.002
  converged_threshold: 0.0001
  max_optim_iter: 200

Tracking:
  initial_pose:
    rot:
      cols: 3
      data:
      - 0.93992945
      - -0.20821672
      - 0.27051511
      - 0.21811915
      - 0.97589900
      - -0.00672095
      - -0.26259602
      - 0.06532174
      - 0.96269227
      dt: d
      rows: 3
    trans:
      cols: 1
      data:
      - 5.94459200
      - 1.47922790
      - -0.65842646
      dt: d
      rows: 3
  initial_vel:
    angular_vel:
    - 0.04814772
    - 0.04794633
    - 0.00379134
    linear_vel:
    - 0.11414605
    - 0.00285491
    - -0.19478575
  save_path: /home/liutao/Project/GS-EVT/results/sofa_normal1
