Gaussian:
  model_params:
    model_path: "/home/liutao/JYA/GS-EVT/data/v_desk/point_cloud.ply"
    background: [0, 0, 0]
    device: "cuda"
    sh_degree: 3

  pipeline_params:
    convert_SHs_python: False
    compute_cov3D_python: False

  calib_params:
    fx: 898.6876142609614
    fy: 898.5200991810121

Event:
  data_path: "/home/liutao/JYA/GS-EVT/data/VECTOR/desk_normal1/events.txt"
  max_events_per_frame: 30000
  filter_threshold: 0.1
  img_width: 640
  img_height: 480
  intrinsic:
    rows: 3
    cols: 3
    dt: "d"
    data: [ 327.32749,    0.     ,  304.97749,
            0.     ,  327.46184,  235.37621,
            0.     ,    0.     ,    1.     ]
  distortion_factors: [-0.031982, 0.041966, -0.000507, -0.001031, 0.000000]

Tracking:
  initial_pose:
    rot:
      rows: 3
      cols: 3
      dt: "d"
      data: [0.96082889,  0.14040014, -0.23894694,
             -0.15915478,  0.98536758, -0.06099581,
             0.22688675,  0.09663608,  0.96911499]
    trans:
      rows: 3
      cols: 1
      dt: "d"
      data: [-3.90670702, 2.03726012, -1.35093176]

  initial_vel:
    angular_vel: [-0.07911462,  -0.03913723,  0.12094993]
    linear_vel: [ 3.06952551, -0.19708658,  1.45889706]

Optimizer:
  max_optim_iter: 200
  converged_threshold: 0.0001
  cam_rot_delta: 0.003
  cam_trans_delta: 0.001
  cam_w_delta: 0.00001
  cam_v_delta: 0.0001